server:
  port: 9091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tnt_utilities
    username: tnt
    password: tnt
    driver-class-name: com.mysql.jdbc.Driver
    
    max-active: 10
    max-idle: 8
    max-wait: 10000
    min-evictable-idle-time-millis: 1000
    min-idle: 8
    time-between-eviction-runs-millis: 1
     
  jpa:
    hibernate:
      naming:
        strategy: SpringPhysicalNamingStrategy
    database: mysql

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${server.port:8080}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${vcap.services.discovery-service.credentials.uri:http://127.0.0.1:8761}/eureka/
      
security.oauth2.resource.userInfoUri: http://tnt-auth-server-oauth.cfapps.io/uaa/user
      
---
spring:
  profiles: cloud
  
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80

flyway:
  validate-on-migrate: false
      